replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/cloudside-academy/lk-repo/cs-app
  tag: "13"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  name: dev
