replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/cloudside-academy/lk-repo/cs-app
  tag: "12"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 9000

env:
  name: dev
